version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 1
    groups:
      npm-dependencies:
        patterns:
          - '*'
        update-types:
          - 'minor'
          - 'patch'
    reviewers:
      - 'johan-gorter'
    commit-message:
      prefix: 'deps'
      include: 'scope'

  # Enable version updates for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 1
    groups:
      github-actions:
        patterns:
          - '*'
    reviewers:
      - 'johan-gorter'
    commit-message:
      prefix: 'ci'
      include: 'scope'

  # Enable version updates for Docker
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '04:00'
    open-pull-requests-limit: 1
    groups:
      docker-dependencies:
        patterns:
          - '*'
    reviewers:
      - 'johan-gorter'
    commit-message:
      prefix: 'docker'
      include: 'scope'
