name: Auto Release on Version Bump

on:
  push:
    branches:
      - main
      - release/*
    # Avoid infinite loops - don't trigger on tags
    tags-ignore:
      - '**'

permissions:
  contents: write
  id-token: write
  attestations: write
  packages: write

jobs:
  check-and-release:
    name: Check Version and Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need history to read previous version

      - name: Read current version
        id: current
        run: echo "version=$(node -p \"require('./package.json').version\")" >> "$GITHUB_OUTPUT"

      - name: Read previous version
        id: previous
        run: |
          if git rev-parse HEAD^ >/dev/null 2>&1; then
            git show HEAD^:package.json > prev_package.json 2>/dev/null || echo '{}' > prev_package.json
            PREV_VERSION=$(node -e "try{console.log(require('./prev_package.json').version||'')}catch(e){console.log('')}")
            echo "version=$PREV_VERSION" >> "$GITHUB_OUTPUT"
          else
            echo "version=" >> "$GITHUB_OUTPUT"
          fi

      - name: Check if release needed
        id: decision
        run: |
          CUR="${{ steps.current.outputs.version }}"
          PREV="${{ steps.previous.outputs.version }}"
          echo "Current: $CUR  Previous: $PREV"

          if [ -z "$CUR" ]; then
            echo "No current version found; abort."
            echo "release_required=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          if [ "$CUR" = "$PREV" ]; then
            echo "Version unchanged."
            echo "release_required=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          TAG="v$CUR"
          git fetch --tags --quiet

          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists; skipping."
            echo "release_required=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi

          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
          echo "version=$CUR" >> "$GITHUB_OUTPUT"
          echo "release_required=true" >> "$GITHUB_OUTPUT"

      - name: Setup Node.js
        if: steps.decision.outputs.release_required == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        if: steps.decision.outputs.release_required == 'true'
        run: npm ci

      - name: Run tests
        if: steps.decision.outputs.release_required == 'true'
        run: npm test

      - name: Build project
        if: steps.decision.outputs.release_required == 'true'
        run: npm run build

      - name: Generate changelog
        if: steps.decision.outputs.release_required == 'true'
        id: changelog
        run: |
          VERSION="${{ steps.decision.outputs.version }}"
          if [ -f CHANGELOG.md ]; then
            CHANGELOG_CONTENT=$(awk '/^## \[?'$VERSION'\]?/{flag=1; next} /^## \[?[0-9]/{flag=0} flag' CHANGELOG.md || echo "")
            if [ -n "$CHANGELOG_CONTENT" ]; then
              echo "CHANGELOG<<EOF" >> $GITHUB_OUTPUT
              echo "$CHANGELOG_CONTENT" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
            else
              echo "CHANGELOG=Release $VERSION" >> $GITHUB_OUTPUT
            fi
          else
            echo "CHANGELOG=Release $VERSION" >> $GITHUB_OUTPUT
          fi

      - name: Build MCPB bundle
        if: steps.decision.outputs.release_required == 'true'
        run: npm run build:mcpb

      - name: Generate artifact attestation for MCPB bundle
        if: steps.decision.outputs.release_required == 'true'
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: '*.mcpb'

      - name: Create GitHub Release
        if: steps.decision.outputs.release_required == 'true'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.decision.outputs.tag }}
          name: Release ${{ steps.decision.outputs.version }}
          body: ${{ steps.changelog.outputs.CHANGELOG }}
          draft: false
          prerelease: ${{ contains(steps.decision.outputs.version, '-') }}
          files: |
            *.mcpb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup docker Image
        if: steps.decision.outputs.release_required == 'true' && !contains(steps.decision.outputs.version, '-')
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.decision.outputs.release_required == 'true' && !contains(steps.decision.outputs.version, '-')
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        if: steps.decision.outputs.release_required == 'true' && !contains(steps.decision.outputs.version, '-')
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Build and push Docker image
        if: steps.decision.outputs.release_required == 'true' && !contains(steps.decision.outputs.version, '-')
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
