name: Security Audit

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    # Run security audit weekly on Mondays at 8:00 AM UTC
    - cron: '0 8 * * 1'

jobs:
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: npm audit
    
    - name: Run dependency vulnerability check
      run: npm audit --audit-level high
    
    - name: Check for outdated packages
      run: npm outdated || true
    
    - name: Generate audit report
      run: |
        echo "## Security Audit Report" > audit-report.md
        echo "Generated on: $(date)" >> audit-report.md
        echo "" >> audit-report.md
        echo "### Vulnerabilities" >> audit-report.md
        npm audit --json > audit.json || true
        echo "\`\`\`json" >> audit-report.md
        cat audit.json >> audit-report.md
        echo "\`\`\`" >> audit-report.md
    
    - name: Upload audit report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-audit-report
        path: |
          audit-report.md
          audit.json
        retention-days: 30